# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=50)),
                ('regist_time', models.DateTimeField()),
                ('remark', models.TextField()),
            ],
            managers=[
                ('users_manage', django.db.models.manager.Manager()),
            ],
        ),
    ]
