# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=200)),
                ('publish_time', models.DateTimeField()),
                ('cover', models.ImageField(default='video/v_default.jpg', upload_to='')),
                ('intro', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoDetailType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('cover', models.ImageField(default='video/t_default.jpg', upload_to='')),
                ('remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('cover', models.ImageField(default='video/t_default.jpg', upload_to='')),
                ('remark', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='videodetailtype',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myvideo.VideoType'),
        ),
        migrations.AddField(
            model_name='video',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myvideo.VideoDetailType'),
        ),
        migrations.AddField(
            model_name='video',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.Users'),
        ),
    ]
