# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField(default=0)),
                ('desc', models.TextField()),
            ],
            managers=[
                ('goods_manage', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GoodsDetailType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
            ],
            managers=[
                ('gdt_manage', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=300)),
                ('isdefault', models.BooleanField(default=False)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshopping.Goods')),
            ],
            managers=[
                ('gi_manage', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
            ],
            managers=[
                ('gt_manage', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ShopCart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deal_time', models.DateTimeField()),
                ('deal_price', models.FloatField()),
                ('deal_count', models.IntegerField()),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshopping.Goods')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.Users')),
            ],
            managers=[
                ('shopcart_manage', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='goodsdetailtype',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshopping.GoodsType'),
        ),
        migrations.AddField(
            model_name='goods',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshopping.GoodsDetailType'),
        ),
    ]
